name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: \${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Zip application
      run: |
        zip -r mi-app.zip app docker-compose.yml

    - name: Upload artifact to S3
      run: |
        aws s3 cp mi-app.zip s3://mi-pipeline-source-\$(aws sts get-caller-identity --query Account --output text)/mi-app.zip
